SportsStore/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class NavController : Controller
    {

        private IProductsRepository repository;

        public NavController(IProductsRepository repo)
        {
            this.repository = repo; 
        }

        public PartialViewResult Menu(String category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<String> categories = this.repository.Products.Select(item => item.Category)
                                                                     .Distinct()
                                                                     .OrderBy(item => item);
            return PartialView(categories);
        }
    }
}

SportsStore/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using System.Web.Mvc;
using System;
using System.Linq;
using SportsStore.Models;
using SportsStore.Domain.Entities;

namespace SportsStore.Controllers
{
    public class ProductController : Controller
    {
        private IProductsRepository repository;
        public Int32 pageSize = 4;

        public ProductController(IProductsRepository productRepository)
        {
            this.repository = productRepository;
        }

        [HttpGet]
        public ViewResult List(String category, Int32 page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel()
            {
                Products = this.repository.Products.Where(item => String.IsNullOrEmpty(category) || (item.Category == category))
                                                   .OrderBy(item => item.ProductID)
                                                   .Skip((page - 1) * this.pageSize)
                                                   .Take(this.pageSize),
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerpage = this.pageSize,
                    TotalItems = this.repository.Products.Where(item => String.IsNullOrEmpty(category) || (item.Category == category)).Count(),
                },
                CurrentCategory = category,
            };
            return View(model);

        }

        public FileContentResult GetImage(Int32 productID)
        {
            Product prop = this.repository.Products.FirstOrDefault(item => item.ProductID == productID);
            if (prop != null)
            {
                return File(prop.ImageData, prop.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product
<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="75" height="75" src="@Url.Action("GetImage","Product",new {Model.ProductID})"/>
        </div>
    }
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(item => item.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add tocart"/>
        </div>

    }
    <span class="lead"> @Model.Description</span>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>    
    <meta name="viewport" content="width=device-width"/>
    <link rel="stylesheet" href="~/Content/bootstrap-theme.css"/>
    <link rel="stylesheet" href="~/Content/bootstrap.css"/>
    <link rel="stylesheet" href="~/Content/ErrorStyles.css"/>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
@using SportsStore.Domain.Entities
@using System.Collections.Generic
@using SportsStore.HtmlHelpers
@*@model SportsStore.Models.ProductsListViewModel*@
@{
    ViewBag.Title = "Products";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">SPORTS STORE</span>
            <div class="visible-xs">SPORTS </div>
            <div class="visible-xs">STORE</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="category" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @*@foreach (var item in Model.Products)
                {
                    <div>
                        <h3>@item.Name</h3>
                        @item.Description
                        <h4>@item.Price.ToString("c")</h4>
                    </div>
                }
                <div>
                    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x }))
                </div>*@
            @RenderBody()
        </div>
    </div>
</body>
</html>